blank_issues_enabled: false
contact_links:
  - name: The Mcpeplay Games Website
    url: https://mcpeplay.ga
    about: The Mcpeplay Games Website
  - name: The Mcpeplay Games Discord
    url: https://dsc.gg/mcpp
    about: Here you can chat or do other things!
